EventEase(2)/EventEase/Controllers/EventsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Hosting;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using EventEase.Data;
using EventEase.Models;
using Microsoft.CodeAnalysis;
using Microsoft.AspNetCore.Identity;
using EventEase.Controllers;



namespace EventEase.Controllers
{
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly RezervationService _reservationService;
        private readonly UserManager<IdentityUser> _userManager;

        public EventsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment, RezervationService reservationService, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _reservationService = reservationService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var events = await _context.Event.Include(e => e.Category).ToListAsync();
            return View(events);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .Include(e => e.Category)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        [Authorize(Roles = "Organizer")]
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryName");
            ViewData["OrganizerId"] = new SelectList(_context.Organizer, "Id", "Name");
            return View();
        }

        [Authorize(Roles = "Organizer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Location,Discription,Date,CategoryId,OrganizerId,Image,ImageFile,TotalTickets,AvailableTickets,Price")] Event @event)
        {
            //if (ModelState.IsValid)
            {
                if (@event.ImageFile != null && @event.ImageFile.Length > 0)
                {
                    var uploadsDir = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                    var fileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(@event.ImageFile.FileName);
                    var filePath = Path.Combine(uploadsDir, fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await @event.ImageFile.CopyToAsync(fileStream);
                    }

                    @event.Image = fileName;
                }

                _context.Add(@event);
                await _context.SaveChangesAsync();

                // Përditëso vlerën e AvailableTickets me vlerën e TotalTickets
                @event.AvailableTickets = @event.TotalTickets;
                _context.Update(@event);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            ViewData["OrganizerId"] = new SelectList(_context.Organizer, "Id", "Name", @event.OrganizerId);
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryName", @event.CategoryId);
            return View(@event);
           
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }

            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryName", @event.CategoryId);
            ViewData["OrganizerId"] = new SelectList(_context.Organizer, "Id", "Name", @event.OrganizerId);
            return View(@event);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Location,Discription,CategoryId,Image,ImageFile")] Event @event)
        {
            if (id != @event.Id)
            {
                return NotFound();
            }

          //  if (ModelState.IsValid)
            {
                try
                {
                    if (@event.ImageFile != null && @event.ImageFile.Length > 0)
                    {
                        var uploadsDir = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                        var fileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(@event.ImageFile.FileName);
                        var filePath = Path.Combine(uploadsDir, fileName);

                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await @event.ImageFile.CopyToAsync(fileStream);
                        }

                        @event.Image = fileName; // Update the image property with the new file name
                    }

                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            // If the model state is not valid, return the view with the event data
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryName", @event.CategoryId);
            ViewData["OrganizerId"] = new SelectList(_context.Organizer, "Id", "Name", @event.OrganizerId);
            return View(@event);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .Include(e => e.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @event = await _context.Event.FindAsync(id);
            _context.Event.Remove(@event);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
            return _context.Event.Any(e => e.Id == id);
        }

        public IActionResult Event(string searchTerm, int? categoryFilter)
        {
            var categories = _context.Category
                .Select(c => new SelectListItem
                {
                    Value = c.CategoryId.ToString(),
                    Text = c.CategoryName
                })
                .ToList();

            ViewBag.Categories = categories;

            var events = _context.Event
                .Include(e => e.Category)
                .Where(e =>
                    (string.IsNullOrEmpty(searchTerm) || e.Discription.Contains(searchTerm)) &&
                    (!categoryFilter.HasValue || e.CategoryId == categoryFilter)
                )
                .ToList();

            if (events.Count == 0)
            {
                ViewBag.NoItemsMessage = "No events found.";
            }

            ViewBag.CategoryFilter = categoryFilter ?? 0;

            return View(events);
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> ReserveTicket(int id)
        {
            var @event = await _context.Event.FindAsync(id);

            if (@event == null)
            {
                return NotFound();
            }

            if (@event.AvailableTickets <= 0)
            {
                ViewBag.ErrorMessage = "Nuk ka më vende të lira për këtë event.";
                return View("Error");
            }

            return View(@event);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmReservation(ReservationModel reservationModel)
        {
            if (ModelState.IsValid)
            {
                var @event = await _context.Event.FindAsync(reservationModel.EventId);

                if (@event == null)
                {
                    return NotFound();
                }

                if (@event.AvailableTickets < reservationModel.NumTickets)
                {
                    ViewBag.ErrorMessage = "Numri i biletave të zgjedhura është më i madh se biletat e disponueshme.";
                    return View("Error");
                }

                decimal totalAmount = reservationModel.NumTickets * @event.Price;

                var reservationSuccessful = await _reservationService.ReserveTicket(@event, reservationModel.UserEmail, reservationModel.NumTickets, totalAmount);

                if (reservationSuccessful)
                {

                    @event.AvailableTickets -= reservationModel.NumTickets;
                    _context.Update(@event);
                    await _context.SaveChangesAsync();

                    ViewBag.SuccessMessage = "Rezervimi u krye me sukses!";
                    return View("Success");

EventEase(2)/EventEase/Controllers/RoleAdminController.cs
using EventEase.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using EventEase.Models;
using EventEase.Areas.Identity.Pages.Account;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EventEase.Controllers
{
    public class RoleAdminController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> UserManager;
        public RoleManager<IdentityRole> RoleManager;
        public IEnumerable<IdentityRole> Roles { get; set; }

        public RoleAdminController(UserManager<IdentityUser> userManager,
        RoleManager<IdentityRole> roleManager, ApplicationDbContext context)
        {
            this.UserManager = userManager;
            this.RoleManager = roleManager;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var users = UserManager.Users.Select(user => new UserDetailsViewModel()
            {
                Id = user.Id,
                UserName = user.UserName,
                Email = user.Email,
                Role = string.Join(",", UserManager.GetRolesAsync(user).Result.ToArray())
            }).ToList();
            return View(users);
        }

        [HttpGet]
        public async Task<IActionResult> ShowEdit(string id)
        {
            var user = await UserManager.FindByIdAsync(id);
            if (id == null)
            {
                return BadRequest("User not found");
            }
            var model = new UserDetailsViewModel
            {
                Id = user.Id,
                Email = user.Email,
                UserName = user.UserName
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(UserDetailsViewModel model)
        {
            var user = await UserManager.FindByIdAsync(model.Id);
            if (user == null)
            {
                return BadRequest("User not found" + model.Id);
            }
            else
            {
                user.Email = model.Email;
                user.UserName = model.UserName;
                var result = await UserManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return View(model);
            }
        }
        public async Task<IActionResult> Delete(string id)
        {
            IdentityUser user = await UserManager.FindByIdAsync(id);
            if (user != null)
            {
                await UserManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<ActionResult> Create(string id)
        {
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return BadRequest("User not found");
            }
            var model = new UserDetailsViewModel
            {
                Id = user.Id,
                Email = user.Email
            };
            var roles = RoleManager.Roles;
            ViewBag.Roles = new SelectList(roles.ToList(), "Id", "Name");
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateUserRole(UserDetailsViewModel u)
        {
            var user = await UserManager.FindByEmailAsync(u.Email);
            if (user == null)
            {
                return BadRequest("User does not exist" + u.Email);
            }

            var name = Convert.ToString(await RoleManager.FindByIdAsync(u.Role));
            if (name == null)
            {
                return BadRequest("Role does not exist" + u.Role);
            }

            await UserManager.AddToRoleAsync(user, name);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<ActionResult> RemoveUserRole(string id)
        {
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return BadRequest("User not found");
            }

            var roles = await UserManager.GetRolesAsync(user);

            ViewBag.Roles = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");

            var model = new UserDetailsViewModel
            {
                Id = user.Id,
                Email = user.Email
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RemoveUserRole(UserDetailsViewModel u)
        {
            var user = await UserManager.FindByIdAsync(u.Id);
            if (user == null)
            {
                return BadRequest("User does not exist" + u.Email);
            }
            if (string.IsNullOrEmpty(u.Role))
            {
                return BadRequest("Role is null or empty");
            }

            var result = await UserManager.RemoveFromRoleAsync(user, u.Role);
            if (result.Succeeded)
            {
                // Ruaj ndryshimet
                await _context.SaveChangesAsync();

                return RedirectToAction("Index"); // Shto këtë rresht për redirektim pasi të ketë sukses
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }

            return View("RemoveUserRole", u);
        }
    }
}

EventEase(2)/EventEase/Views/Admin/Index.cshtml
@model EventEase.Models.AdminDashboard
@{
    ViewData["Title"] = "Admin Panel";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"]</title>
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/admin.css" rel="stylesheet"> <!-- Referenca për skedarin CSS -->
    <link href="~/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
</head>

<body>
    <div id="wrapper">
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Welcome Admin To Dashboard</h1>
                        <div class="row">
                            <div class="col-lg-3 col-md-6">
                                <div class="panel panel-red">
                                    <div class="panel-heading">
                                        <div class="row">
                                            <div class="col-xs-3">
                                                <i class="fa fa-file-text fa-5x"></i>
                                            </div>
                                            <div class="col-xs-9 text-right">
                                                <div class="huge  text-white ">@Model.perdoruesit</div>
                                                <div class="txt">Registrated Users</div>
                                            </div>
                                        </div>
                                    </div>
                                    <a asp-area="" asp-controller="RoleAdmin" asp-action="Index">
                                        <div class="panel-footer">
                                            <span class="pull-left">View Details</span>
                                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                            <div class="clearfix"></div>
                                        </div>
                                    </a>
                                </div>
                            </div>

                            <div class="col-lg-3 col-md-6">
                                <div class="panel panel-yellow">
                                    <div class="panel-heading">
                                        <div class="row">
                                            <div class="col-xs-3">
                                                <i class="fa fa-user fa-5x"></i>
                                            </div>
                                            <div class="col-xs-9 text-right">
                                                <div class="huge text-white">@Model.eventet</div>
                                                <div class="txt">Events</div>
                                            </div>
                                        </div>
                                    </div>
                                    <a asp-area="" asp-controller="Events" asp-action="Index">
                                        <div class="panel-footer">
                                            <span class="pull-left">View Details</span>
                                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                            <div class="clearfix"></div>
                                        </div>
                                    </a>
                                </div>
                            </div>

                            <div class="col-lg-3 col-md-6">
                                <div class="panel panel-red">
                                    <div class="panel-heading">
                                        <div class="row">
                                            <div class="col-xs-3">
                                                <i class="fa fa-list fa-5x"></i>
                                            </div>
                                            <div class="col-xs-9 text-right">
                                                <div class="huge text-white ">@Model.organizatoret</div>
                                                <div class="txt">Organizers</div>
                                            </div>
                                        </div>
                                    </div>
                                    <a asp-area="" asp-controller="Organizers" asp-action="Index">
                                        <div class="panel-footer">
                                            <span class="pull-left">View Details</span>
                                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                            <div class="clearfix"></div>
                                        </div>
                                    </a>
                                </div>
                            </div>

                            <div class="col-lg-3 col-md-6">
                                <div class="panel panel-yellow">
                                    <div class="panel-heading">
                                        <div class="row">
                                            <div class="col-xs-3">
                                                <i class="fa fa-user fa-5x"></i>
                                            </div>
                                            <div class="col-xs-9 text-right">
                                                <div class="huge text-white ">@Model.categorit</div>
                                                <div class="txt">Categories</div>
                                            </div>
                                        </div>
                                    </div>
                                    <a asp-area="" asp-controller="Categories" asp-action="Index">
                                        <div class="panel-footer">
                                            <span class="pull-left">View Details</span>
                                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                            <div class="clearfix"></div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>